export const wordList = [
    "the",
    "be",
    "of",
    "and",
    "a",
    "to",
    "in",
    "he",
    "have",
    "it",
    "that",
    "for",
    "they",
    "I",
    "with",
    "as",
    "not",
    "on",
    "she",
    "at",
    "by",
    "this",
    "we",
    "you",
    "do",
    "but",
    "from",
    "or",
    "which",
    "one",
    "would",
    "all",
    "will",
    "there",
    "say",
    "who",
    "make",
    "when",
    "can",
    "more",
    "if",
    "no",
    "man",
    "out",
    "other",
    "so",
    "what",
    "time",
    "up",
    "go",
    "about",
    "than",
    "into",
    "could",
    "state",
    "only",
    "new",
    "year",
    "some",
    "take",
    "come",
    "these",
    "know",
    "see",
    "use",
    "get",
    "like",
    "then",
    "first",
    "any",
    "work",
    "now",
    "may",
    "such",
    "give",
    "over",
    "think",
    "most",
    "even",
    "find",
    "day",
    "also",
    "after",
    "way",
    "many",
    "must",
    "look",
    "before",
    "great",
    "back",
    "through",
    "long",
    "where",
    "much",
    "should",
    "well",
    "people",
    "down",
    "own",
    "just",
    "because",
    "good",
    "each",
    "those",
    "feel",
    "seem",
    "how",
    "high",
    "too",
    "place",
    "little",
    "world",
    "very",
    "still",
    "nation",
    "hand",
    "old",
    "life",
    "tell",
    "write",
    "become",
    "here",
    "show",
    "house",
    "both",
    "between",
    "need",
    "mean",
    "call",
    "develop",
    "under",
    "last",
    "right",
    "move",
    "thing",
    "general",
    "school",
    "never",
    "same",
    "another",
    "begin",
    "while",
    "number",
    "part",
    "turn",
    "real",
    "leave",
    "might",
    "want",
    "point",
    "form",
    "off",
    "child",
    "few",
    "small",
    "since",
    "against",
    "ask",
    "late",
    "home",
    "interest",
    "large",
    "person",
    "end",
    "open",
    "public",
    "follow",
    "during",
    "present",
    "without",
    "again",
    "hold",
    "govern",
    "around",
    "possible",
    "head",
    "consider",
    "word",
    "program",
    "problem",
    "however",
    "lead",
    "system",
    "set",
    "order",
    "eye",
    "plan",
    "run",
    "keep",
    "face",
    "fact",
    "group",
    "play",
    "stand",
    "increase",
    "early",
    "course",
    "change",
    "help",
    "line"
]
export const THINGS = [
    'cow', 'vegetables', 'car', 'tree', 'cat', 'zebra', 'book', 'bread', 'shoes', 'belt', 'helmet',
    'bulb', 'potato', 'rock', 'door', 'key', 'plane', 'letter', 'sand', 'fire', 'alarm', 'dice',
    'water', 'art', 'song', 'radio', 'pot', 'dishes', 'camera', 'flower', 'sock', 'animal',
];
export const PLACES = [
    'dungeon', 'coast', 'town', 'house', 'garden', 'earth', 'stairs', 'island', 'space', 'place',
    'outside', 'station', 'market', 'cinema', 'tower', 'parking', 'jungle',
];
export const IDEAS = [
    'effect', 'officer', 'king', 'hour', 'idea', 'economy', 'customer', 'power', 'walk', 'think',
    'eat', 'way', 'take', 'through', 'inside', 'deal', 'cast', 'hard', 'hunger', 'liberty', 'very',
    'when', 'for', 'eleven', 'habit', 'daily', 'travel', 'artist', 'butcher',
];
export const THINGS_FR = [
    'salade', 'voiture', 'chat', 'pain', 'ceinture', 'livre', 'ballon', 'drogue', 'truc',
     'ampoule', 'chanson', 'lettre', 'sable', 'feu', 'alarme', 'eau', 'tasse',
    'fleur', 'table', 'pate', 'bague', 'sac', 'riz', 'vache',
];
export const OTHERS_FR = [
    'tombe', 'porte', 'travers', 'dur', 'terre', 'rire', 'trop', 'jour', 'dix', 'faim',
    'route', 'alors', 'zip', 'troupe', 'ville', 'bouton', 'test', 'filet',  'nouveau',
    'os', 'pied', 'poisson',
];
export const SPANISH = [
    'ahora', 'porque', 'pero',  'nosotros', 'nuestro', 'nuestra', 'nada', 'sino', 'madrid',
    'barcelona', 'eso', 'usted', 'digo', 'luis', 'juan', 'francesca', 'entonces',
];
const FURTHER = [
    'expand', 'animals', 'dusty', 'unfasten', 'north', 'texture', 'gullible', 'cemetery', 'slimy',
    'disapprove', 'employ', 'purple', 'pause', 'responsible', 'brawny', 'sneaky', 'match', 'deafening',
    'meddle', 'hour', 'suffer', 'show', 'vacuous', 'squirrel', 'size', 'way', 'secdhand', 'slimy',
    'mammoth', 'murky', 'capable', 'escape', 'majestic', 'cute', 'modern', 'lovely', 'grab', 'society',
    'tickle', 'ill', 'ludicrous', 'spicy', 'possible', 'teytiny', 'friend', 'year', 'reduce',
    'adjustment', 'wealthy', 'tight', 'wave', 'thankful', 'coach', 'knowledge', 'silky', 'development',
    'bang', 'jumbled', 'piquant', 'various', 'curious', 'squash', 'ray', 'hook', 'swift', 'hot',
    'zesty', 'tart', 'hand', 'spotless', 'hope', 'acceptable', 'recognise', 'peck', 'question',
    'grip', 'oatmeal', 'fire', 'twig', 'tow', 'romantic', 'shut', 'nimble', 'caring', 'charge',
    'spoon', 'receipt', 'vast', 'rock', 'head', 'choke', 'welcome', 'fact', 'silver', 'punishment',
    'jittery', 'comfortable', 'crabby', 'earn', 'obedient', 'playground', 'dangerous', 'godly',
    'relieved', 'health', 'long', 'calculating', 'clumsy', 'compete', 'tie', 'risk', 'illustrious',
];
export const EMERGENCY = [...THINGS, ...PLACES, ...IDEAS];

export const ALL_WORDS = [...THINGS, ...PLACES, ...IDEAS, ...THINGS_FR, ...OTHERS_FR, ...SPANISH, ...FURTHER];